### ISSUE TITLE
The document has no pages.

### ISSUE THREAD

**Issue by DafyddNZ** [andyhutch77/MvcRazorToPdf#20]
Hi I am trying to use the MvcRazorToPdf for the first time, but I get an Exception when using PdfActionResult.

[IOException: The document has no pages.]
   iTextSharp.text.pdf.PdfPages.WritePageTree() +1112
   iTextSharp.text.pdf.PdfWriter.Close() +378
   iTextSharp.text.Document.Close() +152
   MvcRazorToPdf.MvcRazorToPdf.GeneratePdfOutput(ControllerContext context, Object model, String viewName, Action`2 configureSettings) +837
   MvcRazorToPdf.PdfActionResult.ExecuteResult(ControllerContext context) +555
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +109
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +241
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +19
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +51
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

Any ideas?

**Comment by lkeel75** [comment]
I still have not heard anything from this.  Is there anyone out there having the same issue?  Has anyone resolved this problem?

**Comment by andyhutch77** [comment]
Hi @lkeel75, sorry I am really short of time both in and outside of work.
I currently don't have any time to look at this. 
I will keep you updated if I get time or if someone else submits a pull request.

**Comment by Lulli** [comment]
Hello, I am experiencing the same error using the same layout and just some basic html in my view.

**Comment by Lulli** [comment]
I solved my solution by passing absolute path to the view when doing return new PdfActionResult
I was using relative.

**Comment by lkeel75** [comment]
I want to thank everyone for their troubles.  Lulli gave me the correct solution.  Once I put the full path in my html to the images, then everything was working as I wanted.  Thanks so much for your time and effort!

**Comment by andyhutch77** [comment]
@lkeel75 Please you managed to get it sorted, I thought it was something a lot more complicated. The demo app has the absolute path and I thought you would have based it upon that. Sorry I didn't pick that up earlier.

**Comment by arthurlv6** [comment]
I found a problem,which the PDF file can't show words properly except English words. Is there anyone who met this problem?

**Comment by rahatur** [comment]
In my case I had itextsharp version 5.5.8.0 and itextsharp.xmlworker version 5.5.5 which was causing the error. I updated the itextsharp.xmlworker to version 5.5.8.0 and it fixed the error!
Asp.net MVC 5.2.3.0
itextsharp 5.5.8.0
itextsharp.xmlworker 5.5.8.0
