### ISSUE TITLE
Charset UTF-8 / Unicode

### ISSUE THREAD

**Issue by marcinkiewicz** [andyhutch77/MvcRazorToPdf#24]
Hi! How could I change charset of output pdf file, because there are some characters missing and they are not rendered in the pdf.

**Comment by chaintan17** [comment]
Thai language is also has this issue too.

**Comment by andyhutch77** [comment]
@chaintan17 Hi, there is an example here (all be it in Java) that displays polish text.

http://stackoverflow.com/questions/29102552/convert-html-to-pdf-by-itext-xmlworker-with-polish-letters
 
http://itextpdf.com/sandbox/xmlworker/ParseHtml2

Please give this a try, the source code is open source so if it works submit a pull request and I will include it.
