### ISSUE TITLE
Wrong dependencies in nuget package

### ISSUE THREAD

**Issue by panicoenlaxbox** [andyhutch77/MvcRazorToPdf#25]
Hi,

I have installed MvcRazorToPdf and I'm have a compiler error with the following description:

Assembly 'MvcRazorToPdf, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'itextsharp, Version=5.5.3.0, Culture=neutral, PublicKeyToken=8354ae6d2174ddca' which has a higher version than referenced assembly 'itextsharp, Version=5.5.0.0, Culture=neutral, PublicKeyToken=8354ae6d2174ddca'...

I had to upgrade the iTextSharp and itextsharp.packages to the 5.5.3 version with the following commands: 

Install-Package iTextSharp -version 5.5.3
Install-Package itextsharp.xmlworker -version 5.5.3

Now, it seems to compile.

Thank you for your excellent job! :)

**Comment by andyhutch77** [comment]
Thanks Sergio.
I will update that when I get a chance.
Take care
Andy

**Comment by nostradamnit** [comment]
I just installed your package from nuget and I have this same error. Is there a way to update it locally? Thx!
