### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by MustafaCali** [andyhutch77/MvcRazorToPdf#26]
Error	1	'System.Web.Mvc.ControllerContext' does not contain a definition for 'GeneratePdf' and no extension method 'GeneratePdf' accepting a first argument of type 'System.Web.Mvc.ControllerContext' could be found (are you missing a using directive or an assembly reference?) How can I resolve the problem?

**Comment by ShaneRoode** [comment]
All I did to fix this issue was to click "Show All Files" in solution explorer and then include MvcRazorToPdfExtensions.cs into the project.

**Comment by MustafaCali** [comment]
thanks :)
