### ISSUE TITLE
Can I use ViewBag instead of passing a model?

### ISSUE THREAD

**Issue by germanger** [andyhutch77/MvcRazorToPdf#30]
Can I use ViewBag instead of passing a model?

eg. Instead of this:

                return new PdfActionResult(someModel, (writer, document) =>
                {
                    document.SetPageSize(new Rectangle(792f, 612f));
                    document.NewPage();
                })
                {
                    FileDownloadName = "foo.pdf"
                };

Something like:

                ViewBag.someModel1 = someModel1;
                ViewBag.someModel2 = someModel2;

                return new PdfActionResult(null, (writer, document) =>
                {
                    document.SetPageSize(new Rectangle(792f, 612f));
                    document.NewPage();
                })
                {
                    FileDownloadName = "foo.pdf"
                };

Why? because I don't like the idea of creating a model only for the purpose of transporting two different objects to that view.

**Comment by andyhutch77** [comment]
Yes, I believe so as the ViewBag is used for the Title in all the examples. :)

**Comment by germanger** [comment]
Awesome! works great!
Thanks.

Maybe there should be an overload for the PdfActionResult constructor so that it is not needed to pass a `null`

Instead of this:

            return new PdfActionResult(null, (writer, document) =>
            {
                document.SetPageSize(new Rectangle(792f, 612f));
                document.NewPage();
            })
            {
                FileDownloadName = "foo.pdf"
            };

Just this:

            return new PdfActionResult((writer, document) =>
            {
                document.SetPageSize(new Rectangle(792f, 612f));
                document.NewPage();
            })
            {
                FileDownloadName = "foo.pdf"
            };

I could make a pull request

**Comment by andyhutch77** [comment]
Yes, I would probably just add a default parameter and initialise it to null, that way we won't need to create an overload but it will achieve the same effect. :+1:

**Comment by germanger** [comment]
Ah right, I would do it that way too

**Comment by germanger** [comment]
Can I use `ControllerContext.GeneratePdf` with ViewBag instead of passing the model?
