### ISSUE TITLE
GeneratePdfOutput from a ApiController 

### ISSUE THREAD

**Issue by zolgera** [andyhutch77/MvcRazorToPdf#42]
Hi!

Ok this is not a bug just I don't know where to put a question

I get it from a class inside a WebAPI call.

I have some arbitrary data that I would like to generate a pdf from

What I need to do looks like is to fake the controllerContext with the data I would like to pass to the view. But I do not know how.

Hope someone can help

**Comment by zolgera** [comment]
Solved it

**Comment by andyhutch77** [comment]
Nice one. 👍🏻
