### ISSUE TITLE
page break

### ISSUE THREAD

**Issue by tvrajja** [andyhutch77/MvcRazorToPdf#48]
This is really impressive. I have a doubt how to give page break for each records in model.

for example:
List<PdfExample> contains multiple records, while generating pdf how to give page break in each records [after pdfexmple[i] i need a page break]
i appreciate your help. thanks raja

**Comment by tvrajja** [comment]
I got it. thanks

**Comment by vip32** [comment]
how? did you manage with normal css?
https://www.w3schools.com/cssref/pr_print_pageba.asp
